// Generated by capnpc-embedded at build time into OUT_DIR.
mod addressbook_capnp {
    include!(concat!(env!("OUT_DIR"), "/addressbook_capnp.rs"));
}

fn main() {
    let mut message = capnp::message::Builder::new_default();
    {
        let book = message.init_root::<addressbook_capnp::address_book::Builder>();
        let mut people = book.init_people(1);
        let mut alice = people.reborrow().get(0);
        alice.set_name("Alice");
        alice.set_email("alice@example.com");
    }
    let reader = message
        .get_root_as_reader::<addressbook_capnp::address_book::Reader>()
        .unwrap();
    let person = reader.get_people().unwrap().get(0);
    println!(
        "person 0: {} <{}>",
        person.get_name().unwrap().to_str().unwrap(),
        person.get_email().unwrap().to_str().unwrap()
    );
}
