use std::path::Path;

// The embedded `capnp.wasm` is generated by `ci/build-wasm.sh`, not committed to
// git. It is present in the *published* crate (produced by the release pipeline
// before `cargo publish`). For a source checkout you must build it once.
fn main() {
    let wasm = Path::new(env!("CARGO_MANIFEST_DIR")).join("assets/capnp.wasm");
    println!("cargo:rerun-if-changed=assets/capnp.wasm");

    if !wasm.exists() {
        panic!(
            "\n\nassets/capnp.wasm is missing.\n\
             This file is generated, not committed to git. Build it once with:\n\n    \
             capnpc-embedded/ci/build-wasm.sh\n\n\
             (requires cmake; downloads wasi-sdk automatically). Published crates on \
             crates.io already include it.\n"
        );
    }
}
